<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblAppointTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_appoint')->delete();
        
        \DB::table('tbl_appoint')->insert(array (
            0 => 
            array (
                'appoint_id' => 1,
                'appoint_time' => '10:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => '2025-10-15',
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'sds',
                'change_history' => '[{"change_type":"status_changed","old_data":{"status":"Approved"},"new_data":{"status":"arrived"},"notes":"Appointment updated","changed_by":"mechelle dee","changed_at":"2025-10-12 06:55:06"},{"change_type":"rescheduled","old_data":{"time":"09:30:00","type":"Check-up"},"new_data":{"time":"10:00","type":"Walk-in"},"notes":"Appointment updated","changed_by":"Jeric Go","changed_at":"2025-10-15 10:07:20"},{"change_type":"rescheduled","old_data":{"time":"10:00:00"},"new_data":{"time":"10:00"},"notes":"Appointment updated","changed_by":"Jeric Go","changed_at":"2025-10-15 10:58:20"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 547,
                'ref_id' => NULL,
                'user_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2025-10-15 08:59:30',
            ),
            1 => 
            array (
                'appoint_id' => 2,
                'appoint_time' => '14:00:00',
                'appoint_status' => 'arrived',
                'reschedule_count' => 0,
                'original_date' => '2025-10-16',
                'appoint_date' => '2025-10-16',
                'last_rescheduled_at' => NULL,
                'appoint_description' => NULL,
                'change_history' => '[{"change_type":"status_changed","old_data":{"status":"Approved"},"new_data":{"status":"arrived"},"notes":"Appointment updated","changed_by":"Marjie Dulanan","changed_at":"2025-10-11 13:07:20"}]',
                'appoint_type' => 'Consultation',
                'pet_id' => 567,
                'ref_id' => NULL,
                'user_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'appoint_id' => 591,
                'appoint_time' => '09:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-11',
                'last_rescheduled_at' => NULL,
                'appoint_description' => NULL,
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-11","time":"09:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-10 13:18:17"},{"change_type":"status_changed","old_data":{"status":"pending"},"new_data":{"status":"arrived"},"notes":"Appointment updated","changed_by":"Marjie Dulanan","changed_at":"2025-10-11 13:08:07"},{"change_type":"status_changed","old_data":{"status":"arrived"},"new_data":{"status":"completed"},"notes":"Appointment updated","changed_by":"Jane","changed_at":"2025-10-11 13:34:58"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 567,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'appoint_id' => 592,
                'appoint_time' => '11:00:00',
                'appoint_status' => 'rescheduled',
                'reschedule_count' => 0,
                'original_date' => '2025-10-11',
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'jhj',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-11","time":"16:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-11 04:10:24"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 562,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2025-10-16 05:00:02',
            ),
            4 => 
            array (
                'appoint_id' => 593,
                'appoint_time' => '13:00:00',
                'appoint_status' => 'rescheduled',
                'reschedule_count' => 0,
                'original_date' => '2025-10-11',
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'smkds',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-11","time":"11:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-11 06:07:58"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 550,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2025-10-16 05:00:04',
            ),
            5 => 
            array (
                'appoint_id' => 594,
                'appoint_time' => '09:00:00',
                'appoint_status' => 'rescheduled',
                'reschedule_count' => 0,
                'original_date' => '2025-10-11',
                'appoint_date' => '2025-10-16',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'shhsh',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-11","time":"11:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-11 07:04:16"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 549,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2025-10-16 05:00:06',
            ),
            6 => 
            array (
                'appoint_id' => 595,
                'appoint_time' => '09:00:00',
                'appoint_status' => 'arrived',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-12',
                'last_rescheduled_at' => NULL,
                'appoint_description' => NULL,
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-12","time":"09:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-11 12:48:19"},{"change_type":"status_changed","old_data":{"status":"refer"},"new_data":{"status":"arrived"},"notes":"Appointment updated","changed_by":"mechelle dee","changed_at":"2025-10-11 13:16:05"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 548,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'appoint_id' => 597,
                'appoint_time' => '13:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-10',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'rttr',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-10","time":"13:00","status":"completed","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-11 13:36:33"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 549,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'appoint_id' => 598,
                'appoint_time' => '09:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-11',
                'last_rescheduled_at' => NULL,
                'appoint_description' => NULL,
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-11","time":"13:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-11 13:37:14"},{"change_type":"status_changed","old_data":{"status":"pending"},"new_data":{"status":"completed"},"notes":"Appointment updated","changed_by":"Jane","changed_at":"2025-10-11 13:38:02"},{"change_type":"rescheduled","old_data":{"time":"13:00:00"},"new_data":{"time":"09:00"},"notes":"Appointment updated","changed_by":"Jane","changed_at":"2025-10-11 13:39:01"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 554,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'appoint_id' => 600,
                'appoint_time' => '17:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-12',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'gg',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-12","time":"17:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-12 07:28:37"},{"change_type":"rescheduled","old_data":{"time":"17:00:00"},"new_data":{"time":"13:00"},"notes":"Appointment updated","changed_by":"Jeric Go","changed_at":"2025-10-13 04:31:35"},{"change_type":"rescheduled","old_data":{"time":"13:00:00","status":"arrived"},"new_data":{"time":"17:00","status":"completed"},"notes":"Appointment updated","changed_by":"mechelle dee","changed_at":"2025-10-13 11:10:45"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 549,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => NULL,
                'updated_at' => '2025-10-13 09:10:45',
            ),
            10 => 
            array (
                'appoint_id' => 601,
                'appoint_time' => '16:00:00',
                'appoint_status' => 'arrived',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-13',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'jlfdjgl',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-13","time":"16:00","status":"arrived","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-13 10:40:13"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 556,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => '2025-10-13 08:40:13',
                'updated_at' => '2025-10-13 08:40:13',
            ),
            11 => 
            array (
                'appoint_id' => 603,
                'appoint_time' => '17:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-13',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'hhhg',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-13","time":"17:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-13 10:46:34"},{"change_type":"rescheduled","old_data":{"time":"17:00:00","status":"pending"},"new_data":{"time":"17:00","status":"completed"},"notes":"Appointment updated","changed_by":"mechelle dee","changed_at":"2025-10-13 10:46:57"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 555,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-13 08:46:34',
                'updated_at' => '2025-10-13 08:46:57',
            ),
            12 => 
            array (
                'appoint_id' => 604,
                'appoint_time' => '11:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-13',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'dkfksj',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-13","time":"11:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-13 11:21:01"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 549,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-13 09:21:01',
                'updated_at' => '2025-10-15 04:14:58',
            ),
            13 => 
            array (
                'appoint_id' => 606,
                'appoint_time' => '14:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-20',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'send dose',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-20","time":"14:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-13 11:27:52"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 564,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-13 09:27:52',
                'updated_at' => '2025-10-15 01:58:18',
            ),
            14 => 
            array (
                'appoint_id' => 607,
                'appoint_time' => '09:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-22',
                'last_rescheduled_at' => NULL,
                'appoint_description' => '2in 1',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-22","time":"09:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-15 02:35:01"},{"change_type":"rescheduled","old_data":{"time":"09:00:00","status":"pending"},"new_data":{"time":"09:00","status":"arrived"},"notes":"Appointment updated","changed_by":"Jane","changed_at":"2025-10-15 02:47:46"},{"change_type":"rescheduled","old_data":{"time":"09:00:00","status":"arrived"},"new_data":{"time":"09:00","status":"completed"},"notes":"Appointment updated","changed_by":"Jane","changed_at":"2025-10-15 02:48:03"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 550,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => '2025-10-15 00:35:01',
                'updated_at' => '2025-10-15 00:48:03',
            ),
            15 => 
            array (
                'appoint_id' => 609,
                'appoint_time' => '15:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'askjd',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-15","time":"15:00","status":"arrived","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-15 06:46:43"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 552,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-15 04:46:43',
                'updated_at' => '2025-10-15 04:50:42',
            ),
            16 => 
            array (
                'appoint_id' => 611,
                'appoint_time' => '16:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'ijlkjl',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-15","time":"16:00","status":"arrived","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-15 07:18:57"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 565,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-15 05:18:57',
                'updated_at' => '2025-10-15 05:19:26',
            ),
            17 => 
            array (
                'appoint_id' => 612,
                'appoint_time' => '15:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'kjlkj',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-15","time":"15:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-15 07:22:49"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 559,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-15 05:22:49',
                'updated_at' => '2025-10-15 05:23:15',
            ),
            18 => 
            array (
                'appoint_id' => 613,
                'appoint_time' => '15:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'lklk',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-15","time":"15:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-15 07:26:23"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 561,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-15 05:26:23',
                'updated_at' => '2025-10-15 05:27:02',
            ),
            19 => 
            array (
                'appoint_id' => 614,
                'appoint_time' => '14:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'zjhjfhdjf',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-15","time":"14:00","status":"arrived","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-15 07:31:19"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 556,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-15 05:31:19',
                'updated_at' => '2025-10-15 05:31:46',
            ),
            20 => 
            array (
                'appoint_id' => 615,
                'appoint_time' => '16:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-16',
                'last_rescheduled_at' => NULL,
                'appoint_description' => NULL,
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-16","time":"16:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"mechelle dee","changed_at":"2025-10-15 11:14:15"},{"change_type":"rescheduled","old_data":{"time":"16:00:00"},"new_data":{"time":"16:00"},"notes":"Appointment updated","changed_by":"mechelle dee","changed_at":"2025-10-15 11:19:27"},{"change_type":"status_changed","old_data":{"status":"pending"},"new_data":{"status":"completed"},"notes":"Appointment updated","changed_by":"mechelle dee","changed_at":"2025-10-15 11:20:19"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 562,
                'ref_id' => NULL,
                'user_id' => 30,
                'created_at' => '2025-10-15 09:14:15',
                'updated_at' => '2025-10-15 09:20:19',
            ),
            21 => 
            array (
                'appoint_id' => 616,
                'appoint_time' => '09:00:00',
                'appoint_status' => 'completed',
                'reschedule_count' => 0,
                'original_date' => NULL,
                'appoint_date' => '2025-10-15',
                'last_rescheduled_at' => NULL,
                'appoint_description' => 'vaccine',
                'change_history' => '[{"change_type":"created","old_data":null,"new_data":{"date":"2025-10-15","time":"09:00","status":"pending","type":"Walk-in"},"notes":"Appointment created","changed_by":"Jane","changed_at":"2025-10-15 15:08:57"}]',
                'appoint_type' => 'Walk-in',
                'pet_id' => 548,
                'ref_id' => NULL,
                'user_id' => 28,
                'created_at' => '2025-10-15 21:08:57',
                'updated_at' => '2025-10-15 21:15:42',
            ),
        ));
        
        
    }
}